Adfluencer_package/views.py
import os
from flask import Blueprint, Response, Flask, session
from flask import request, render_template, url_for, redirect, flash
from flask_login import login_user, login_required, logout_user, current_user
from flask import render_template, request
from Adfluencer_package.models import users
from werkzeug.security import generate_password_hash, check_password_hash
from Adfluencer_package import db, create_app, app
from werkzeug.utils import secure_filename
from Adfluencer_package.models import advertisements
from Adfluencer_package.models import advt_approval
import rec_sys as model

app = Flask(__name__)
UPLOAD_FOLDER = 'static/uploads'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
basedir = os.path.abspath(os.path.dirname(__file__))
views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('index.html')


@views.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('pswd')
        user_a = users.query.filter_by(comp_email=email).first()
        user_i = users.query.filter_by(inf_email=email).first()
        if user_a:
            if check_password_hash(user_a.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user_a, remember=True)
                return redirect('/advt/dashboard')
            else:
                flash('Incorrect password, try again.', category='error')

        elif user_i:
            if check_password_hash(user_i.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user_i, remember=True)
                return redirect('/infl/dashboard')
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist', category='error')
    return render_template('login.html')


@views.route('/logout')
@login_required
def logout():
    logout_user()
    flash("logged out successfully!", category='success')
    return redirect(url_for('views.home'))


@views.route('/advt/dashboard', methods = ['GET', 'POST'])
@login_required
def advt_dashboard():
    if current_user.comp_name == None:
        flash('Please login')
        return redirect(url_for('views.login'))
    else:
        name = current_user.comp_name
        recmd_infl = model.recm_sys(name)
        owner_id = current_user.id
        advts_owner= advertisements.query.all()
        advts = advertisements.query.filter_by(owner_id=owner_id)
        advts_oid = advertisements.query.filter_by(owner_id=owner_id).first()
        recmd_infl.remove(owner_id)
        # print(recmd_infl)
        for tar_id in recmd_infl:
            tar_inf = users.query.filter_by(id=tar_id).first()
            tar_id = tar_inf.id
            if tar_inf.acc_type == 'advt':
                recmd_infl.remove(tar_id)
            else:
                continue
        print(recmd_infl)
        
        main=[]
        for inf_id in recmd_infl[:12]:
            inf = users.query.filter_by(id=inf_id)
            for infl in inf:
                i = infl.id
                f = infl.fname
                l = infl.lname
                c = infl.categories
                s = infl.smh
                n = infl.infl_pic
                abc=[]
                abc.append(f)
                abc.append(l)
                abc.append(c)
                abc.append(s)
                abc.append(n)
                abc.append(i)
                main.append(abc)
        print(main)
        try:
            adv_oid = advts_oid.owner_id
            if adv_oid:
                return render_template('advt_dashboard.html',advts=advts, name=name, advts_owner=advts_owner, adv_oid=adv_oid, owner_id=owner_id,main = main)
            else:
                return render_template('advt_dashboard.html',advts=advts, name=name, advts_owner=advts_owner, owner_id=owner_id, main = main)
        except:
            return render_template('advt_dashboard.html',advts=advts, name=name, advts_owner=advts_owner, owner_id=owner_id, main = main)


def allowed_file(filename):
    return '.' in filename and \
            filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/advt/advertise', methods = ['GET', 'POST'])
@login_required
def advt_advertise():
    if current_user.comp_name == None:
        flash('Please login')
        return redirect(url_for('views.login'))
    else:
        if request.method == 'POST':
            files = request.files.getlist('prdt_imgs')
            for file in files:
                if file and allowed_file(file.filename):
                    comp_name = current_user.comp_name
                    email = current_user.comp_email
                    desc = request.form.get('desc')
                    brand = request.form.get('brand')
                    deadline = request.form.get('deadline')
                    prdt_sp = request.form.get('prdt_sp')
                    age_grp = request.form.get('age_grp')
                    prdt_imgs = request.files['prdt_imgs']
                    owner_id = current_user.id
                    
                    filename = secure_filename(prdt_imgs.filename)
                    mimetype = prdt_imgs.mimetype
                    
                    file.save(os.path.join(basedir, app.config['UPLOAD_FOLDER'], filename))
                    advt = advertisements(owner_id=owner_id, comp_name=comp_name, email=email, desc=desc, brand=brand, deadline=deadline, prdt_sp=prdt_sp,
                    age_grp=age_grp, name = filename, mimetype=mimetype)
                    db.session.add(advt)
                    db.session.commit()
                    flash('Advertisement added!', category='success')
                    return redirect(url_for('views.advt_dashboard'))
                else:
                    flash('Please upload a valid image file (JPEG/JPG/PNG/GIF).')
                    user_email=current_user.comp_email
                    comp_name = current_user.comp_name
                    return render_template('advt_advertisements.html',user_email=user_email, comp_name=comp_name)
        
        user_email=current_user.comp_email
        comp_name = current_user.comp_name
        return render_template('advt_advertisements.html', user_email=user_email, comp_name=comp_name)

@views.route('/advt/update_advertise/<int:id>', methods = ['GET', 'POST'])
@login_required
def advt_update(id):
    name_to_update = advertisements.query.filter(advertisements.id==id).first()
    advt = advertisements.query.filter_by(id=id).first()
    advt_name_update = advertisements.query.filter_by(id=id).first()
    files = request.files.getlist('prdt_imgs')
    for file in files:
        if file and allowed_file(file.filename):
            name_to_update.desc = request.form.get('desc')
            name_to_update.brand = request.form.get('brand')
            name_to_update.deadline = request.form.get('deadline')
            name_to_update.prdt_sp = request.form.get('prdt_sp')
            name_to_update.age_grp = request.form.get('age_grp')
            name_to_update.prdt_imgs = request.files['prdt_imgs']
            filename = secure_filename(name_to_update.prdt_imgs.filename)  
            name_to_update.name = filename
            advt_name_update.advt_name = filename
            try:
                file.save(os.path.join(basedir, app.config['UPLOAD_FOLDER'], filename))
                db.session.commit()                    
                flash('Database updated successfully!')
                return redirect(url_for('views.advt_dashboard'))
            except:
                file.save(os.path.join(basedir, app.config['UPLOAD_FOLDER'], filename))
                db.session.commit()                    
                flash('Database updated successfully!')
                return redirect(url_for('views.advt_dashboard'))

    advt_id = id
    user_email = current_user.comp_email
    advts = advertisements.query.filter_by(id=advt_id).first()
    return render_template('advt_update_advertisements.html',advt=advt, advts=advts, user_email=user_email, id=advt_id )

@views.route('/advt/delete_advertise/<int:id>')
@login_required
def advt_delete(id):
    advt_to_delete = advertisements.query.get_or_404(id)
    advta_to_delete = advt_approval.query.filter_by(advt_id=id).first()
    try:
        if advt_to_delete:
            db.session.delete(advt_to_delete)
            db.session.commit()
        elif advta_to_delete:
            db.session.delete(advta_to_delete)
            db.session.commit()
        flash('Advertisement deleted successfully!')
        return redirect(url_for('views.advt_dashboard'))
    except:
        flash('some error occured')
        return redirect(url_for('views.advt_dashboard'))


@views.route('/advt/applications/<int:id>', methods = ['GET', 'POST'])
@login_required
def advt_apply(id):
    advt_id = id    
    apl = advt_approval.query.filter_by(advt_id=advt_id, approved=0).all()        
    advts = advertisements.query.filter_by(id=advt_id).first()
    return render_template('advt_applications.html', advt=advts,apl=apl)


@views.route('/advt/approved_applications/<int:id>', methods = ['GET', 'POST'])
@login_required
def advt_app_applicants(id):
    advt_id = id    
    apl = advt_approval.query.filter_by(advt_id=advt_id, approved=1).all()        
    advts = advertisements.query.filter_by(id=advt_id).first()
    return render_template('advt_approved_applicants.html', advt=advts,apl=apl)


@views.route('/advt/applications/approve/<int:id>', methods = ['GET', 'POST'])
@login_required
def advt_approve(id):
    advt_apr = advt_approval.query.filter_by(id=id).first()
    advt_apr.approved=1
    advt_apr.filter='approved'
    advta_id = advt_apr.advt_id
    db.session.commit()

Adfluencer_package/templates/advt_advertisements.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AdFluencer</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="../static/img/Logo_1.png" rel="icon">
    <link href="../static/img/Logo_1.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../static/vendor/aos/aos.css" rel="stylesheet">
    <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="../static/css/style.css" rel="stylesheet">

    <!-- Including jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js">
    </script>

    <!-- Including Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js">
    </script>

    <!-- Including validation -->
    <script type="text/javascript" src="{{url_for('static', filename='js/advt_advertisement.js' )}}"></script>
</head>

<body>
    <div class="wrap">

        <!-- ======= Header ======= -->
        <header id="header" class="d-flex align-items-center">
            <div class="container d-flex align-items-center justify-content-between">

                <div class="logo">
                    <h1 class="text-light"><a href="{{url_for('views.advt_dashboard')}}"><span>AdFluencer</span></a>
                    </h1>                    
                </div>

                <nav id="navbar" class="navbar">
                    <ul>
                        <li><a class="nav-link scrollto " href="{{url_for('views.advt_dashboard')}}">Home</a></li>
                        <li><a href="{{url_for('views.logout')}}">Logout</a></li>
                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav><!-- .navbar -->

            </div>
        </header><!-- End Header -->
    </div>

    <br><br><br>
    {% for msg in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    
    <body onload="firstfocus()"></body>
    <form name='advertisements' enctype=multipart/form-data method="POST" onsubmit="return validate()" >
        <br>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Company Name</label>
            <input type="text" class="form-control" name="comp_name" id="exampleFormControlInput1"
                placeholder="{{ comp_name }}" value="{{ comp_name }}" disabled>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" name="email" id="exampleFormControlInput1"
                placeholder="{{ user_email }}" value="{{ user_email }}" disabled>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Product's Description</label>
            <textarea class="form-control" name="desc" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Product's name</label>
            <input type="text" class="form-control" name="brand" id="inputAddress" placeholder="">
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Deadline</label>
            <input type="text" class="form-control" name="deadline" id="inputAddress" placeholder="">
        </div>
        <div class="col-12">
            <label for="exampleFormControlTextarea1" class="form-label">Product's selling points</label>
            <textarea class="form-control" name="prdt_sp" id="exampleFormControlTextarea1" rows="3"></textarea>            
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Age group targeted</label>
            <input type="text" class="form-control" name="age_grp" id="inputAddress" placeholder="">
        </div>
        <div class="mb-3">
            <label for="formFileMultiple" class="form-label">Upload product's image</label>
            <input class="form-control" type="file" name="prdt_imgs" id="formFileMultiple">
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Save and Upload</button>
        </div>
    </form>
    <br>
    <style>
        form {
            padding-left: 50px;
            padding-right: 50px;
        }
    </style>
    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>AdFluencer</h3>
                        <p>
                            1st Floor, Lok Centre Premises Co-op Society Ltd Above ICICI Bank, Marol Maroshi Rd, Marol,
                            Andheri East, Mumbai <br><br>
                            <strong>Phone:</strong> +91 858846718<br>
                            <strong>Email:</strong> contact@adfluencer.com<br>
                        </p>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Social Networks</h4>

                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="github"><i class="bx bxl-github"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container py-4">
            <div class="copyright">
                &copy; Copyright <strong><span>AdFluencer</span></strong>. All Rights Reserved
            </div>
        </div>
    </footer><!-- End Footer -->

    </div>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/aos/aos.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/php-email-form/validate.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>

    <!-- Template Main JS File -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>

</body>

</html>

Adfluencer_package/templates/advt_applications.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AdFluencer</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{url_for('static', filename='img/Logo_1.png')}}" rel="icon">
    <link href="{{url_for('static', filename='img/Logo_1.png')}}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{url_for('static',filename='css/style.css')}}" rel="stylesheet">

</head>

<body>
    <div class="wrap">

        <!-- ======= Header ======= -->
        <header id="header" class="d-flex align-items-center">
            <div class="container d-flex align-items-center justify-content-between">

                <div class="logo">
                    <h1 class="text-light"><a href="{{url_for('views.advt_dashboard')}}"><span>AdFluencer</span></a>
                    </h1>
                </div>

                <nav id="navbar" class="navbar">
                    <ul>
                        <li><a class="nav-link scrollto " href="{{url_for('views.advt_dashboard')}}">Home</a></li>
                        <li><a href="{{url_for('views.logout')}}">Logout</a></li>
                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav><!-- .navbar -->

            </div>
        </header><!-- End Header -->

        <style>
            .breadcrumbs{
                padding-top: 100px;
            }
        </style>
        <main id="main">
            
            <!-- ======= Breadcrumbs ======= -->
            <section id="breadcrumbs" class="breadcrumbs" data-aos="fade-up">
                <div class="container">

                    <div class="d-flex justify-content-between align-items-center">
                        <h2>Advertisement Details </h2>
                        <ol>
                            <li><a href="{{url_for('views.advt_dashboard')}}">Home</a></li>
                            <li><a href="{{url_for('views.advt_details', advt_id=advt.id)}}">Advertisement</a></li>
                            <li><a href="{{url_for('views.advt_apply', id=advt.id)}}">Applications</a></li>                            
                        </ol>
                    </div>

                </div>
            </section><!-- End Breadcrumbs -->
            {% for msg in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        <script type="text/javascript">
            setTimeout(function () {
    
                // Closing the alert
                $('.alert').alert('close');
            }, 3000);
        </script>
            <!-- ======= Portfolio Details Section ======= -->
            <section id="portfolio-details" class="portfolio-details">
                <div class="container">

                    <div class="row gy-4">

                        <div class="col-lg-8">
                            <div class="portfolio-details-slider swiper-container">
                                <div class="swiper-wrapper align-items-center">

                                    <div class="swiper-slide">
                                        <img src="{{ url_for('static', filename = 'uploads/'+advt.name) }}"
                                            class="img-fluid" alt="{{ advt.name }}">
                                    </div>

                                </div>
                                <div class="swiper-pagination"></div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="portfolio-info">
                                <h3>Project information</h3>
                                <ul>
                                    <li><strong>Company: </strong> {{advt.comp_name}}</li>
                                    <li><strong>Brand: </strong> {{advt.brand}}</li>
                                    <li><strong>Deadline: </strong>{{ advt.deadline }}</li>
                                    <li><strong>Product selling points: </strong>{{ advt.prdt_sp }}</li>
                                    <li><strong>Age group targeted:</strong> {{ advt.age_grp }}</li>
                                </ul>
                            </div>
                            <div class="portfolio-description">
                                <h2>Product Description</h2>
                                <p>
                                    {{ advt.desc }}
                                </p>
                            </div>
                            <a href="{{url_for('views.advt_app_applicants', id= advt.id)}}" class="btn btn-primary btn-lg">Approved Applicants</a>
                            
                        </div>
                        <h2>Applicants for your advertisement</h2>
                        <div class="table-wrapper-scroll-y my-custom-scrollbar">
                            <table class="table table-hover">
                                <tbody>
                                    {% if apl|length==0 %}
                                        <div class="alert alert-dark" role="alert">
                                        No applications yet
                                        </div>                                    
                                    {% else %}                                                                                                        
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">First Name</th>
                                                <th scope="col">Last Name</th>
                                                <th scope="col">Social Media Handle</th>
                                                <th scope="col">Email</th>
                                            </tr>
                                        </thead>
                                            {% for item in apl %}
                                            <tr>
                                                <th scope="row">{{loop.index}}</th>
                                                <td>{{item.infl_fname}}</td>
                                                <td>{{item.infl_lname}}</td>
                                                <td>{{item.infl_smh}}</td>
                                                <td>{{item.infl_email}}</td>
                                                <td>
                                                    <a href="{{url_for('views.advt_approve', id=item.id)}}" type="button"
                                                        class="btn btn-outline-success btn-sn mx-1">Approve</button>
                                                </td>
                                                <td>
                                                    <a href="{{url_for('views.advt_reject', id=item.id)}}" type="button"
                                                    class="btn btn-outline-danger btn-sn mx-1">Reject</button>
                                                    
                                                </td>
                                            </tr>
                                        {% endfor %}                                
                                        {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

            </section><!-- End Portfolio Details Section -->

        </main><!-- End #main -->

        <!-- ======= Footer ======= -->
        <footer id="footer">

            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h3>AdFluencer</h3>
                            <p>
                                1st Floor, Lok Centre Premises Co-op Society Ltd Above ICICI Bank, Marol Maroshi Rd,
                                Marol, Andheri East, Mumbai <br><br>
                                <strong>Phone:</strong> +91 858846718<br>
                                <strong>Email:</strong> contact@adfluencer.com<br>
                            </p>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-links">

                        </div>
                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Our Social Networks</h4>

                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="github"><i class="bx bxl-github"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="container py-4">
                <div class="copyright">
                    &copy; Copyright <strong><span>AdFluencer</span></strong>. All Rights Reserved
                </div>
            </div>
        </footer><!-- End Footer -->

    </div>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{{url_for('static', filename='vendor/aos/aos.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/php-email-form/validate.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>

    <!-- Template Main JS File -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>

</body>

</html>